SELECT A.ITEM_ID, B.ITEM_NAME, B.RARITY
FROM ITEM_TREE A
LEFT OUTER JOIN ITEM_INFO B
ON A.ITEM_ID = B.ITEM_ID
LEFT OUTER JOIN ITEM_INFO C
ON A.PARENT_ITEM_ID = C.ITEM_ID
WHERE C.RARITY = 'RARE'
ORDER BY A.ITEM_ID DESC;