SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
LEFT OUTER JOIN CAR_RENTAL_COMPANY_CAR B
ON A.CAR_ID = B.CAR_ID
WHERE B.CAR_TYPE = '세단' AND MONTH(START_DATE) = '10'
ORDER BY 1 DESC;